export type CookLanguage = "en" | "hi" | "te";

export const cookLanguageNames: Record<CookLanguage, string> = {
    en: "English",
    hi: "हिन्दी",
    te: "తెలుగు",
};

export function parseCookLanguage(value: unknown): CookLanguage {
    if (value === "hi" || value === "hindi") return "hi";
    if (value === "te" || value === "telugu") return "te";
    return "en";
}

const translations: Record<"hi" | "te", Record<string, string>> = {
    hi: {
        "Booking notifications": "बुकिंग सूचनाएँ",
        "Enabling notifications...": "सूचनाएँ चालू हो रही हैं...",
        "Unable to save notification device.": "सूचना पाने वाला उपकरण सहेजा नहीं जा सका।",
        "Notification registration timed out.": "सूचना पंजीकरण का समय समाप्त हो गया।",
        "My Profile": "मेरी प्रोफ़ाइल",
        "Profile": "प्रोफ़ाइल",
        "Service Areas": "सेवा क्षेत्र",
        "Language": "भाषा",
        "App Language": "ऐप की भाषा",
        "Home": "होम",
        "Bookings": "बुकिंग",
        "Earnings": "कमाई",
        "Go back": "वापस जाएँ",
        "Manage your personal details and preferences.": "अपनी जानकारी और प्राथमिकताएँ प्रबंधित करें।",
        "Your availability": "आपकी उपलब्धता",
        "You're online": "आप ऑनलाइन हैं",
        "You're offline": "आप ऑफ़लाइन हैं",
        "Availability unavailable": "उपलब्धता की जानकारी नहीं है",
        "Checking your availability...": "उपलब्धता जाँची जा रही है...",
        "You can receive booking requests.": "आपको बुकिंग अनुरोध मिल सकते हैं।",
        "Go online to receive booking requests.": "बुकिंग अनुरोध पाने के लिए ऑनलाइन हों।",
        "Cook profile not found.": "कुक प्रोफ़ाइल नहीं मिली।",
        "Profile Approved": "प्रोफ़ाइल स्वीकृत",
        "Your profile has been verified and is visible to customers.": "आपकी प्रोफ़ाइल सत्यापित है और ग्राहकों को दिख रही है।",
        "Approved": "स्वीकृत",
        "Personal Information": "व्यक्तिगत जानकारी",
        "Full Name": "पूरा नाम",
        "Phone Number": "फ़ोन नंबर",
        "Email Address": "ईमेल पता",
        "Date of Birth": "जन्म तिथि",
        "Gender": "लिंग",
        "Female": "महिला",
        "Languages Spoken": "बोली जाने वाली भाषाएँ",
        "Cooking Details": "खाना पकाने की जानकारी",
        "Cooking Experience": "खाना पकाने का अनुभव",
        "Cuisines": "व्यंजन शैलियाँ",
        "Special Dishes": "विशेष व्यंजन",
        "Preferred Meal Types": "पसंदीदा भोजन प्रकार",
        "About Me": "मेरे बारे में",
        "Address": "पता",
        "House / Flat No.": "घर / फ़्लैट नंबर",
        "Street / Area / Locality": "गली / क्षेत्र / मोहल्ला",
        "City": "शहर",
        "Pincode": "पिन कोड",
        "Landmark": "नज़दीकी पहचान",
        "Service Area": "सेवा क्षेत्र",
        "Documents": "दस्तावेज़",
        "Loading uploaded documents...": "अपलोड किए गए दस्तावेज़ लोड हो रहे हैं...",
        "No documents uploaded.": "कोई दस्तावेज़ अपलोड नहीं किया गया।",
        "Logout": "लॉग आउट",
        "Edit": "संपादित करें",
        "View": "देखें",
        "Notifications": "सूचनाएँ",
        "Push notifications": "पुश सूचनाएँ",
        "Notifications enabled": "सूचनाएँ चालू हैं",
        "Stay updated": "अपडेट पाते रहें",
        "This device is registered for cook notifications.": "यह डिवाइस कुक सूचनाओं के लिए पंजीकृत है।",
        "Get alerts for new booking requests on this device.": "इस डिवाइस पर नए बुकिंग अनुरोधों की सूचना पाएँ।",
        "Enable notifications": "सूचनाएँ चालू करें",
        "Enabling...": "चालू किया जा रहा है...",
        "Hello, Lakshmi!": "नमस्ते, लक्ष्मी!",
        "Here's your cooking journey at a glance.": "आपकी कुकिंग यात्रा की एक झलक।",
        "Checking...": "जाँच हो रही है...",
        "Unavailable": "उपलब्ध नहीं",
        "Pending": "लंबित",
        "Nov 2024": "नवंबर 2024",
        "16 Nov 2024": "16 नवंबर 2024",
        "Profile status unavailable": "प्रोफ़ाइल की स्थिति उपलब्ध नहीं है",
        "Sign in to check status": "स्थिति देखने के लिए लॉग इन करें",
        "Cook profile not found": "कुक प्रोफ़ाइल नहीं मिली",
        "Unknown profile status": "प्रोफ़ाइल की स्थिति ज्ञात नहीं है",
        "Service areas are unavailable.": "सेवा क्षेत्र उपलब्ध नहीं हैं।",
        "Please sign in to manage service areas.": "सेवा क्षेत्र प्रबंधित करने के लिए लॉग इन करें।",
        "Unable to load service areas.": "सेवा क्षेत्र लोड नहीं हो सके।",
        "Please sign in again to save service areas.": "सेवा क्षेत्र सहेजने के लिए दोबारा लॉग इन करें।",
        "Unable to save service areas.": "सेवा क्षेत्र सहेजे नहीं जा सके।",
        "Unable to load language preference.": "भाषा की प्राथमिकता लोड नहीं हो सकी।",
        "Unable to save language preference.": "भाषा की प्राथमिकता सहेजी नहीं जा सकी।",
        "Apply the cook language database migration first.": "पहले कुक भाषा का डेटाबेस माइग्रेशन लागू करें।",
        "Unable to register this device.": "इस डिवाइस को पंजीकृत नहीं किया जा सका।",
        "Notifications are blocked. Enable them in your browser settings.": "सूचनाएँ अवरुद्ध हैं। इन्हें ब्राउज़र की सेटिंग में चालू करें।",
        "Enable notifications to register this browser.": "इस ब्राउज़र को पंजीकृत करने के लिए सूचनाएँ चालू करें।",
        "Unable to enable notifications.": "सूचनाएँ चालू नहीं हो सकीं।",
        "Unable to enable notifications on this device.": "इस डिवाइस पर सूचनाएँ चालू नहीं हो सकीं।",
        "Rejected": "अस्वीकृत",
        "Confirmed": "पुष्टि की गई",
        "Loading profile status": "प्रोफ़ाइल की स्थिति लोड हो रही है",
        "Your profile is verified": "आपकी प्रोफ़ाइल सत्यापित है",
        "Awaiting admin review": "व्यवस्थापक की समीक्षा की प्रतीक्षा है",
        "Review your application": "अपना आवेदन देखें",
        "Go offline": "ऑफ़लाइन हों",
        "Be online": "ऑनलाइन हों",
        "Saving...": "सहेजा जा रहा है...",
        "Total Earnings": "कुल कमाई",
        "This Month": "इस महीने",
        "Completed Bookings": "पूरी हुई बुकिंग",
        "Avg. per Booking": "प्रति बुकिंग औसत",
        "Pending Payout": "बकाया भुगतान",
        "Upcoming Bookings": "आगामी बुकिंग",
        "Past Bookings": "पिछली बुकिंग",
        "View all": "सभी देखें",
        "Recent Earnings": "हाल की कमाई",
        "Lunch (4 people)": "दोपहर का भोजन (4 लोग)",
        "Completed": "पूर्ण",
        "Breakfast": "नाश्ता",
        "Lunch": "दोपहर का भोजन",
        "Dinner": "रात का भोजन",
        "Accept": "स्वीकार करें",
        "Reject": "अस्वीकार करें",
        "Booking accepted successfully.": "बुकिंग स्वीकार कर ली गई।",
        "Booking declined.": "बुकिंग अस्वीकार कर दी गई।",
        "You are online.": "आप ऑनलाइन हैं।",
        "You are offline.": "आप ऑफ़लाइन हैं।",
        "Notifications enabled on this device.": "इस डिवाइस पर सूचनाएँ चालू हैं।",
        "Select the societies where you can accept cooking requests.": "वे सोसायटी चुनें जहाँ आप खाना पकाने के अनुरोध स्वीकार कर सकते हैं।",
        "selected": "चयनित",
        "Loading service areas...": "सेवा क्षेत्र लोड हो रहे हैं...",
        "Selected service areas": "चयनित सेवा क्षेत्र",
        "Unavailable society": "अनुपलब्ध सोसायटी",
        "No service areas selected yet.": "अभी कोई सेवा क्षेत्र नहीं चुना गया है।",
        "Remove": "हटाएँ",
        "Search societies": "सोसायटी खोजें",
        "Search societies or areas": "सोसायटी या क्षेत्र खोजें",
        "Filter by city": "शहर के अनुसार छाँटें",
        "Filter by area": "क्षेत्र के अनुसार छाँटें",
        "All cities": "सभी शहर",
        "All areas": "सभी क्षेत्र",
        "Clear visible": "दिख रहे चयन हटाएँ",
        "Select all visible": "दिख रहे सभी चुनें",
        "available": "उपलब्ध",
        "No societies match these filters.": "इन फ़िल्टर से कोई सोसायटी नहीं मिली।",
        "Save service areas": "सेवा क्षेत्र सहेजें",
        "Service areas saved.": "सेवा क्षेत्र सहेजे गए।",
        "Booking Request": "बुकिंग अनुरोध",
        "This booking is waiting for your response": "यह बुकिंग आपके जवाब की प्रतीक्षा में है",
        "Please accept or reject within 12 hours.": "कृपया 12 घंटे के भीतर स्वीकार या अस्वीकार करें।",
        "Booking summary": "बुकिंग का सारांश",
        "people": "लोग",
        "View on map": "नक्शे पर देखें",
        "Customer Details": "ग्राहक की जानकारी",
        "Name": "नाम",
        "Meal Details": "भोजन की जानकारी",
        "Menu": "मेनू",
        "Special Instructions": "विशेष निर्देश",
        "Estimated Earnings": "अनुमानित कमाई",
        "Total Amount": "कुल राशि",
        "Payment Method": "भुगतान का तरीका",
        "Online (via app)": "ऑनलाइन (ऐप से)",
        "Booking accepted.": "बुकिंग स्वीकार कर ली गई।",
        "Booking rejected.": "बुकिंग अस्वीकार कर दी गई।",
        "Register as a Cook": "कुक के रूप में पंजीकरण करें",
        "Tell us about yourself and start cooking with Vantavaru.": "अपने बारे में बताएँ और वंतवारु के साथ खाना पकाना शुरू करें।",
        "Basic Details": "मूल जानकारी",
        "Review": "समीक्षा",
        "Step 1 of 4": "चरण 1 / 4",
        "Step 2 of 4": "चरण 2 / 4",
        "Step 3 of 4": "चरण 3 / 4",
        "Step 4 of 4": "चरण 4 / 4",
        "Enter your full name": "अपना पूरा नाम दर्ज करें",
        "Phone number": "फ़ोन नंबर",
        "Date of birth": "जन्म तिथि",
        "This will be used for login and communication.": "इसका उपयोग लॉगिन और संपर्क के लिए होगा।",
        "Male": "पुरुष",
        "Other": "अन्य",
        "Select experience": "अनुभव चुनें",
        "Less than 1 year": "1 वर्ष से कम",
        "1–3 years": "1–3 वर्ष",
        "3–5 years": "3–5 वर्ष",
        "5+ years": "5+ वर्ष",
        "Cuisines You Cook": "आप कौन-से व्यंजन पकाते हैं",
        "Select cuisines": "व्यंजन शैलियाँ चुनें",
        "Select languages": "भाषाएँ चुनें",
        "South Indian": "दक्षिण भारतीय",
        "North Indian": "उत्तर भारतीय",
        "Chinese": "चीनी",
        "Continental": "कॉन्टिनेंटल",
        "Baking": "बेकिंग",
        "English": "अंग्रेज़ी",
        "Hindi": "हिन्दी",
        "Telugu": "तेलुगु",
        "Tamil": "तमिल",
        "Kannada": "कन्नड़",
        "Profile Photo": "प्रोफ़ाइल फ़ोटो",
        "Upload Photo": "फ़ोटो अपलोड करें",
        "JPG, PNG (Max 5 MB)": "JPG, PNG (अधिकतम 5 MB)",
        "Use a clear photo": "स्पष्ट फ़ोटो का उपयोग करें",
        "Your face should be clearly visible": "आपका चेहरा स्पष्ट दिखना चाहिए",
        "Good lighting helps build trust": "अच्छी रोशनी विश्वास बढ़ाती है",
        "This photo will be visible to customers": "यह फ़ोटो ग्राहकों को दिखेगी",
        "Details Saved": "जानकारी सहेजी गई",
        "Save & Continue": "सहेजें और आगे बढ़ें",
        "Your basic details are saved. Next: address.": "आपकी जानकारी सहेज ली गई है। अगला: पता।",
        "Your Address": "आपका पता",
        "This helps us show you to nearby customers.": "इससे आसपास के ग्राहक आपकी प्रोफ़ाइल देख सकेंगे।",
        "Address Details": "पते की जानकारी",
        "Enter house or flat number": "घर या फ़्लैट नंबर दर्ज करें",
        "Enter street, area or locality": "गली, क्षेत्र या मोहल्ला दर्ज करें",
        "Select city": "शहर चुनें",
        "Enter pincode": "पिन कोड दर्ज करें",
        "(Optional)": "(वैकल्पिक)",
        "e.g. Near Metro Station, City Mall": "जैसे मेट्रो स्टेशन या मॉल के पास",
        "We will show your profile to customers in and around this location.": "इस स्थान के आसपास के ग्राहकों को आपकी प्रोफ़ाइल दिखेगी।",
        "Back": "वापस",
        "Upload Documents": "दस्तावेज़ अपलोड करें",
        "These documents help us verify your identity and keep our community safe.": "इन दस्तावेज़ों से आपकी पहचान सत्यापित करने में मदद मिलती है।",
        "Upload a clear photo of yourself": "अपनी स्पष्ट फ़ोटो अपलोड करें",
        "Photo Guidelines": "फ़ोटो के निर्देश",
        "Use good lighting": "अच्छी रोशनी रखें",
        "Avoid blurred or cropped photos": "धुंधली या कटी हुई फ़ोटो न दें",
        "Aadhaar Card": "आधार कार्ड",
        "Upload a clear copy of your Aadhaar card (front and back)": "आधार कार्ड की दोनों ओर की स्पष्ट प्रति अपलोड करें",
        "2 files selected": "2 फ़ाइलें चुनी गईं",
        "Aadhaar Guidelines": "आधार के निर्देश",
        "Image should be clear and readable": "चित्र स्पष्ट और पढ़ने योग्य होना चाहिए",
        "All corners should be visible": "सभी कोने दिखने चाहिए",
        "File size should be less than 5 MB": "फ़ाइल 5 MB से कम होनी चाहिए",
        "We use this only for verification purposes": "इसका उपयोग केवल सत्यापन के लिए होगा",
        "Additional ID": "अतिरिक्त पहचान पत्र",
        "You can upload PAN card, Driving license or Voter ID": "पैन कार्ड, ड्राइविंग लाइसेंस या मतदाता पहचान पत्र अपलोड कर सकते हैं",
        "Accepted Documents": "स्वीकृत दस्तावेज़",
        "PAN Card": "पैन कार्ड",
        "Driving License": "ड्राइविंग लाइसेंस",
        "Voter ID": "मतदाता पहचान पत्र",
        "This helps us with additional verification (optional).": "इससे अतिरिक्त सत्यापन में मदद मिलेगी (वैकल्पिक)।",
        "Documents Saved": "दस्तावेज़ सहेजे गए",
        "Upload Front Side": "सामने का भाग अपलोड करें",
        "Upload Back Side": "पीछे का भाग अपलोड करें",
        "Tap to upload photo": "फ़ोटो अपलोड करने के लिए टैप करें",
        "File selected": "फ़ाइल चुनी गई",
        "JPG, PNG, PDF (Max 5 MB)": "JPG, PNG, PDF (अधिकतम 5 MB)",
        "Done": "हो गया",
        "You can select multiple": "एक से अधिक चुन सकते हैं",
        "Review your details": "अपनी जानकारी जाँचें",
        "Review your details before submitting your application.": "आवेदन भेजने से पहले अपनी जानकारी जाँचें।",
        "Not provided": "नहीं दिया गया",
        "Not selected": "नहीं चुना गया",
        "Not uploaded": "अपलोड नहीं किया गया",
        "Front & Back Uploaded": "दोनों ओर अपलोड किया गया",
        "Optional": "वैकल्पिक",
        "Within 5 km": "5 किमी के भीतर",
        "Your details will be verified by our team. We'll notify you once your account is approved.": "हमारी टीम आपकी जानकारी सत्यापित करेगी। खाता स्वीकृत होने पर हम आपको सूचित करेंगे।",
        "Submitting...": "भेजा जा रहा है...",
        "Submit Application": "आवेदन भेजें",
        "By submitting, you agree to our": "आवेदन भेजकर आप हमारी",
        "Terms & Conditions": "नियम और शर्तें स्वीकार करते हैं",
        "Submitting your cook application": "आपका कुक आवेदन भेजा जा रहा है",
        "Submitting your application...": "आपका आवेदन भेजा जा रहा है...",
        "Uploading documents and saving your details.": "दस्तावेज़ अपलोड और जानकारी सहेजी जा रही है।",
        "Uploaded Documents": "अपलोड किए गए दस्तावेज़",
        "Back to documents": "दस्तावेज़ों पर वापस जाएँ",
        "Close documents": "दस्तावेज़ बंद करें",
        "No documents have been uploaded.": "कोई दस्तावेज़ अपलोड नहीं किया गया है।",
        "Status": "स्थिति",
        "document": "दस्तावेज़",
        "documents": "दस्तावेज़",
        "Opening...": "खोला जा रहा है...",
        "Open document": "दस्तावेज़ खोलें",
        "Download document": "दस्तावेज़ डाउनलोड करें",
        "Preview is not available for this file type.": "इस फ़ाइल का पूर्वावलोकन उपलब्ध नहीं है।",
        "Registration progress": "पंजीकरण की प्रगति",
        "Snacks": "नाश्ते के व्यंजन",
        "Idli": "इडली",
        "Sambar": "सांभर",
        "Chapati": "चपाती",
        "Vegetable Curry": "सब्ज़ी की करी",
        "I love cooking healthy and tasty home-style meals with fresh ingredients.": "मुझे ताज़ी सामग्री से स्वस्थ और स्वादिष्ट घर जैसा खाना पकाना पसंद है।",
        "Aadhaar Front": "आधार का सामने का भाग",
        "Aadhaar Back": "आधार का पीछे का भाग",
        "Unable to update availability.": "उपलब्धता बदल नहीं सकी।",
        "Unable to open this document.": "यह दस्तावेज़ नहीं खुल सका।",
        "Please sign in again to view your documents.": "दस्तावेज़ देखने के लिए दोबारा लॉग इन करें।",
        "Documents are unavailable because Supabase is not configured.": "सेवा कॉन्फ़िगर नहीं है, इसलिए दस्तावेज़ उपलब्ध नहीं हैं।",
        "Please sign in to change language.": "भाषा बदलने के लिए लॉग इन करें।",
        "Connect Supabase before submitting your application.": "आवेदन भेजने से पहले सेवा कॉन्फ़िगर करें।",
        "Your session has expired. Please log in again.": "आपका सत्र समाप्त हो गया है। दोबारा लॉग इन करें।",
        "Unable to save your cook profile.": "आपकी कुक प्रोफ़ाइल सहेजी नहीं जा सकी।",
        "Unable to go online.": "ऑनलाइन नहीं हो सके।",
        "Unable to go offline.": "ऑफ़लाइन नहीं हो सके।",
        "Notifications are blocked. Enable them in your device settings.": "सूचनाएँ अवरुद्ध हैं। इन्हें डिवाइस की सेटिंग में चालू करें।",
        "Push notifications are not supported in this browser.": "यह ब्राउज़र पुश सूचनाओं का समर्थन नहीं करता।",
        "Please sign in again to enable notifications.": "सूचनाएँ चालू करने के लिए दोबारा लॉग इन करें।",
        "Notifications are not configured.": "सूचना सेवा कॉन्फ़िगर नहीं है।",
    },
    te: {
        "Booking notifications": "బుకింగ్ నోటిఫికేషన్‌లు",
        "Enabling notifications...": "నోటిఫికేషన్‌లు ప్రారంభిస్తున్నాం...",
        "Unable to save notification device.": "నోటిఫికేషన్ పరికరాన్ని సేవ్ చేయలేకపోయాం.",
        "Notification registration timed out.": "నోటిఫికేషన్ నమోదు సమయం ముగిసింది.",
        "My Profile": "నా ప్రొఫైల్",
        "Profile": "ప్రొఫైల్",
        "Service Areas": "సేవా ప్రాంతాలు",
        "Language": "భాష",
        "App Language": "యాప్ భాష",
        "Home": "హోమ్",
        "Bookings": "బుకింగ్‌లు",
        "Earnings": "ఆదాయం",
        "Go back": "వెనక్కి వెళ్లండి",
        "Manage your personal details and preferences.": "మీ వ్యక్తిగత వివరాలు మరియు ప్రాధాన్యతలను నిర్వహించండి.",
        "Your availability": "మీ అందుబాటు",
        "You're online": "మీరు ఆన్‌లైన్‌లో ఉన్నారు",
        "You're offline": "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
        "Availability unavailable": "అందుబాటు సమాచారం లేదు",
        "Checking your availability...": "మీ అందుబాటును తనిఖీ చేస్తున్నాం...",
        "You can receive booking requests.": "మీరు బుకింగ్ అభ్యర్థనలను అందుకోవచ్చు.",
        "Go online to receive booking requests.": "బుకింగ్ అభ్యర్థనల కోసం ఆన్‌లైన్‌లోకి రండి.",
        "Cook profile not found.": "వంటవారి ప్రొఫైల్ కనుగొనబడలేదు.",
        "Profile Approved": "ప్రొఫైల్ ఆమోదించబడింది",
        "Your profile has been verified and is visible to customers.": "మీ ప్రొఫైల్ ధృవీకరించబడింది మరియు కస్టమర్లకు కనిపిస్తుంది.",
        "Approved": "ఆమోదించబడింది",
        "Personal Information": "వ్యక్తిగత సమాచారం",
        "Full Name": "పూర్తి పేరు",
        "Phone Number": "ఫోన్ నంబర్",
        "Email Address": "ఈమెయిల్ చిరునామా",
        "Date of Birth": "పుట్టిన తేదీ",
        "Gender": "లింగం",
        "Female": "మహిళ",
        "Languages Spoken": "మాట్లాడే భాషలు",
        "Cooking Details": "వంట వివరాలు",
        "Cooking Experience": "వంట అనుభవం",
        "Cuisines": "వంటకాల రకాలు",
        "Special Dishes": "ప్రత్యేక వంటకాలు",
        "Preferred Meal Types": "ఇష్టమైన భోజన రకాలు",
        "About Me": "నా గురించి",
        "Address": "చిరునామా",
        "House / Flat No.": "ఇల్లు / ఫ్లాట్ నంబర్",
        "Street / Area / Locality": "వీధి / ప్రాంతం",
        "City": "నగరం",
        "Pincode": "పిన్ కోడ్",
        "Landmark": "గుర్తింపు స్థలం",
        "Service Area": "సేవా ప్రాంతం",
        "Documents": "పత్రాలు",
        "Loading uploaded documents...": "అప్‌లోడ్ చేసిన పత్రాలు లోడ్ అవుతున్నాయి...",
        "No documents uploaded.": "పత్రాలు అప్‌లోడ్ చేయలేదు.",
        "Logout": "లాగ్ అవుట్",
        "Edit": "సవరించు",
        "View": "చూడండి",
        "Notifications": "నోటిఫికేషన్‌లు",
        "Push notifications": "పుష్ నోటిఫికేషన్‌లు",
        "Notifications enabled": "నోటిఫికేషన్‌లు ప్రారంభమయ్యాయి",
        "Stay updated": "తాజా సమాచారం పొందండి",
        "This device is registered for cook notifications.": "ఈ పరికరం వంటవారి నోటిఫికేషన్‌ల కోసం నమోదు చేయబడింది.",
        "Get alerts for new booking requests on this device.": "ఈ పరికరంలో కొత్త బుకింగ్ అభ్యర్థనల హెచ్చరికలు పొందండి.",
        "Enable notifications": "నోటిఫికేషన్‌లు ప్రారంభించండి",
        "Enabling...": "ప్రారంభిస్తున్నాం...",
        "Hello, Lakshmi!": "నమస్కారం, లక్ష్మి!",
        "Here's your cooking journey at a glance.": "మీ వంట ప్రయాణం ఒక చూపులో.",
        "Checking...": "తనిఖీ చేస్తున్నాం...",
        "Unavailable": "అందుబాటులో లేదు",
        "Pending": "పెండింగ్‌లో ఉంది",
        "Rejected": "తిరస్కరించబడింది",
        "Confirmed": "ధృవీకరించబడింది",
        "Loading profile status": "ప్రొఫైల్ స్థితిని లోడ్ చేస్తున్నాం",
        "Your profile is verified": "మీ ప్రొఫైల్ ధృవీకరించబడింది",
        "Awaiting admin review": "నిర్వాహకుడి సమీక్ష కోసం వేచి ఉంది",
        "Review your application": "మీ దరఖాస్తును చూడండి",
        "Go offline": "ఆఫ్‌లైన్‌లోకి వెళ్లండి",
        "Be online": "ఆన్‌లైన్‌లోకి రండి",
        "Saving...": "సేవ్ చేస్తున్నాం...",
        "Total Earnings": "మొత్తం ఆదాయం",
        "This Month": "ఈ నెల",
        "Completed Bookings": "పూర్తయిన బుకింగ్‌లు",
        "Avg. per Booking": "బుకింగ్‌కు సగటు",
        "Pending Payout": "పెండింగ్ చెల్లింపు",
        "Upcoming Bookings": "రాబోయే బుకింగ్‌లు",
        "Past Bookings": "గత బుకింగ్‌లు",
        "View all": "అన్నీ చూడండి",
        "Recent Earnings": "ఇటీవలి ఆదాయం",
        "Lunch (4 people)": "మధ్యాహ్న భోజనం (4 వ్యక్తులు)",
        "Completed": "పూర్తయింది",
        "Breakfast": "అల్పాహారం",
        "Lunch": "మధ్యాహ్న భోజనం",
        "Dinner": "రాత్రి భోజనం",
        "Accept": "అంగీకరించండి",
        "Reject": "తిరస్కరించండి",
        "Booking accepted successfully.": "బుకింగ్ అంగీకరించబడింది.",
        "Booking declined.": "బుకింగ్ తిరస్కరించబడింది.",
        "You are online.": "మీరు ఆన్‌లైన్‌లో ఉన్నారు.",
        "You are offline.": "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు.",
        "Notifications enabled on this device.": "ఈ పరికరంలో నోటిఫికేషన్‌లు ప్రారంభమయ్యాయి.",
        "Select the societies where you can accept cooking requests.": "మీరు వంట అభ్యర్థనలు స్వీకరించే సొసైటీలను ఎంచుకోండి.",
        "selected": "ఎంచుకున్నవి",
        "Loading service areas...": "సేవా ప్రాంతాలు లోడ్ అవుతున్నాయి...",
        "Selected service areas": "ఎంచుకున్న సేవా ప్రాంతాలు",
        "Unavailable society": "సొసైటీ అందుబాటులో లేదు",
        "No service areas selected yet.": "ఇంకా సేవా ప్రాంతాలను ఎంచుకోలేదు.",
        "Remove": "తొలగించండి",
        "Search societies": "సొసైటీలను వెతకండి",
        "Search societies or areas": "సొసైటీలు లేదా ప్రాంతాలు వెతకండి",
        "Filter by city": "నగరం వారీగా వడపోయండి",
        "Filter by area": "ప్రాంతం వారీగా వడపోయండి",
        "All cities": "అన్ని నగరాలు",
        "All areas": "అన్ని ప్రాంతాలు",
        "Clear visible": "కనిపించేవి తొలగించండి",
        "Select all visible": "కనిపించేవన్నీ ఎంచుకోండి",
        "available": "అందుబాటులో ఉన్నాయి",
        "No societies match these filters.": "ఈ ఫిల్టర్‌లకు సరిపోయే సొసైటీలు లేవు.",
        "Save service areas": "సేవా ప్రాంతాలు సేవ్ చేయండి",
        "Service areas saved.": "సేవా ప్రాంతాలు సేవ్ అయ్యాయి.",
        "Booking Request": "బుకింగ్ అభ్యర్థన",
        "This booking is waiting for your response": "ఈ బుకింగ్ మీ సమాధానం కోసం వేచి ఉంది",
        "Please accept or reject within 12 hours.": "దయచేసి 12 గంటల్లో అంగీకరించండి లేదా తిరస్కరించండి.",
        "Booking summary": "బుకింగ్ సారాంశం",
        "people": "వ్యక్తులు",
        "View on map": "మ్యాప్‌లో చూడండి",
        "Customer Details": "కస్టమర్ వివరాలు",
        "Name": "పేరు",
        "Meal Details": "భోజన వివరాలు",
        "Menu": "మెనూ",
        "Special Instructions": "ప్రత్యేక సూచనలు",
        "Estimated Earnings": "అంచనా ఆదాయం",
        "Total Amount": "మొత్తం మొత్తం",
        "Payment Method": "చెల్లింపు విధానం",
        "Online (via app)": "ఆన్‌లైన్ (యాప్ ద్వారా)",
        "Booking accepted.": "బుకింగ్ అంగీకరించబడింది.",
        "Booking rejected.": "బుకింగ్ తిరస్కరించబడింది.",
        "Nov 2024": "నవంబర్ 2024",
        "16 Nov 2024": "16 నవంబర్ 2024",
        "Profile status unavailable": "ప్రొఫైల్ స్థితి అందుబాటులో లేదు",
        "Sign in to check status": "స్థితి చూడటానికి లాగిన్ అవ్వండి",
        "Cook profile not found": "వంటవారి ప్రొఫైల్ కనుగొనబడలేదు",
        "Unknown profile status": "ప్రొఫైల్ స్థితి తెలియదు",
        "Service areas are unavailable.": "సేవా ప్రాంతాలు అందుబాటులో లేవు.",
        "Please sign in to manage service areas.": "సేవా ప్రాంతాలను నిర్వహించడానికి లాగిన్ అవ్వండి.",
        "Unable to load service areas.": "సేవా ప్రాంతాలను లోడ్ చేయలేకపోయాం.",
        "Please sign in again to save service areas.": "సేవా ప్రాంతాలను సేవ్ చేయడానికి మళ్లీ లాగిన్ అవ్వండి.",
        "Unable to save service areas.": "సేవా ప్రాంతాలను సేవ్ చేయలేకపోయాం.",
        "Unable to load language preference.": "భాష ప్రాధాన్యతను లోడ్ చేయలేకపోయాం.",
        "Unable to save language preference.": "భాష ప్రాధాన్యతను సేవ్ చేయలేకపోయాం.",
        "Apply the cook language database migration first.": "ముందుగా వంటవారి భాష డేటాబేస్ మైగ్రేషన్‌ను అమలు చేయండి.",
        "Unable to register this device.": "ఈ పరికరాన్ని నమోదు చేయలేకపోయాం.",
        "Notifications are blocked. Enable them in your browser settings.": "నోటిఫికేషన్‌లు నిలిపివేయబడ్డాయి. బ్రౌజర్ సెట్టింగ్స్‌లో ప్రారంభించండి.",
        "Enable notifications to register this browser.": "ఈ బ్రౌజర్ నమోదు కోసం నోటిఫికేషన్‌లు ప్రారంభించండి.",
        "Unable to enable notifications.": "నోటిఫికేషన్‌లు ప్రారంభించలేకపోయాం.",
        "Unable to enable notifications on this device.": "ఈ పరికరంలో నోటిఫికేషన్‌లు ప్రారంభించలేకపోయాం.",
        "Register as a Cook": "వంటవారిగా నమోదు చేసుకోండి",
        "Tell us about yourself and start cooking with Vantavaru.": "మీ వివరాలు తెలియజేసి వంటవారుతో వంట ప్రారంభించండి.",
        "Basic Details": "ప్రాథమిక వివరాలు",
        "Review": "సమీక్ష",
        "Step 1 of 4": "దశ 1 / 4",
        "Step 2 of 4": "దశ 2 / 4",
        "Step 3 of 4": "దశ 3 / 4",
        "Step 4 of 4": "దశ 4 / 4",
        "Enter your full name": "మీ పూర్తి పేరు నమోదు చేయండి",
        "Phone number": "ఫోన్ నంబర్",
        "Date of birth": "పుట్టిన తేదీ",
        "This will be used for login and communication.": "లాగిన్ మరియు సంప్రదింపుల కోసం ఉపయోగిస్తాం.",
        "Male": "పురుషుడు",
        "Other": "ఇతరులు",
        "Select experience": "అనుభవాన్ని ఎంచుకోండి",
        "Less than 1 year": "1 సంవత్సరం కంటే తక్కువ",
        "1–3 years": "1–3 సంవత్సరాలు",
        "3–5 years": "3–5 సంవత్సరాలు",
        "5+ years": "5+ సంవత్సరాలు",
        "Cuisines You Cook": "మీరు చేసే వంటకాలు",
        "Select cuisines": "వంటకాల రకాలు ఎంచుకోండి",
        "Select languages": "భాషలు ఎంచుకోండి",
        "South Indian": "దక్షిణ భారతీయ",
        "North Indian": "ఉత్తర భారతీయ",
        "Chinese": "చైనీస్",
        "Continental": "కాంటినెంటల్",
        "Baking": "బేకింగ్",
        "English": "ఇంగ్లీష్",
        "Hindi": "హిందీ",
        "Telugu": "తెలుగు",
        "Tamil": "తమిళం",
        "Kannada": "కన్నడ",
        "Profile Photo": "ప్రొఫైల్ ఫోటో",
        "Upload Photo": "ఫోటో అప్‌లోడ్ చేయండి",
        "JPG, PNG (Max 5 MB)": "JPG, PNG (గరిష్ఠం 5 MB)",
        "Use a clear photo": "స్పష్టమైన ఫోటో ఉపయోగించండి",
        "Your face should be clearly visible": "మీ ముఖం స్పష్టంగా కనిపించాలి",
        "Good lighting helps build trust": "మంచి వెలుతురు నమ్మకాన్ని పెంచుతుంది",
        "This photo will be visible to customers": "ఈ ఫోటో కస్టమర్లకు కనిపిస్తుంది",
        "Details Saved": "వివరాలు సేవ్ అయ్యాయి",
        "Save & Continue": "సేవ్ చేసి కొనసాగించండి",
        "Your basic details are saved. Next: address.": "మీ వివరాలు సేవ్ అయ్యాయి. తర్వాత: చిరునామా.",
        "Your Address": "మీ చిరునామా",
        "This helps us show you to nearby customers.": "దీంతో సమీప కస్టమర్లకు మీ ప్రొఫైల్ కనిపిస్తుంది.",
        "Address Details": "చిరునామా వివరాలు",
        "Enter house or flat number": "ఇల్లు లేదా ఫ్లాట్ నంబర్ నమోదు చేయండి",
        "Enter street, area or locality": "వీధి లేదా ప్రాంతం నమోదు చేయండి",
        "Select city": "నగరం ఎంచుకోండి",
        "Enter pincode": "పిన్ కోడ్ నమోదు చేయండి",
        "(Optional)": "(ఐచ్ఛికం)",
        "e.g. Near Metro Station, City Mall": "ఉదా: మెట్రో స్టేషన్ లేదా మాల్ దగ్గర",
        "We will show your profile to customers in and around this location.": "ఈ ప్రాంతం చుట్టూ ఉన్న కస్టమర్లకు మీ ప్రొఫైల్ చూపిస్తాం.",
        "Back": "వెనక్కి",
        "Upload Documents": "పత్రాలు అప్‌లోడ్ చేయండి",
        "These documents help us verify your identity and keep our community safe.": "మీ గుర్తింపును ధృవీకరించడానికి ఈ పత్రాలు ఉపయోగపడతాయి.",
        "Upload a clear photo of yourself": "మీ స్పష్టమైన ఫోటో అప్‌లోడ్ చేయండి",
        "Photo Guidelines": "ఫోటో మార్గదర్శకాలు",
        "Use good lighting": "మంచి వెలుతురు ఉపయోగించండి",
        "Avoid blurred or cropped photos": "అస్పష్టమైన లేదా కత్తిరించిన ఫోటోలు వద్దు",
        "Aadhaar Card": "ఆధార్ కార్డు",
        "Upload a clear copy of your Aadhaar card (front and back)": "ఆధార్ కార్డు రెండు వైపుల స్పష్టమైన ప్రతిని అప్‌లోడ్ చేయండి",
        "2 files selected": "2 ఫైళ్లు ఎంచుకున్నారు",
        "Aadhaar Guidelines": "ఆధార్ మార్గదర్శకాలు",
        "Image should be clear and readable": "చిత్రం స్పష్టంగా చదవదగ్గదిగా ఉండాలి",
        "All corners should be visible": "అన్ని మూలలు కనిపించాలి",
        "File size should be less than 5 MB": "ఫైల్ పరిమాణం 5 MB కంటే తక్కువగా ఉండాలి",
        "We use this only for verification purposes": "ధృవీకరణ కోసం మాత్రమే ఉపయోగిస్తాం",
        "Additional ID": "అదనపు గుర్తింపు పత్రం",
        "You can upload PAN card, Driving license or Voter ID": "పాన్ కార్డు, డ్రైవింగ్ లైసెన్స్ లేదా ఓటరు ఐడీ అప్‌లోడ్ చేయవచ్చు",
        "Accepted Documents": "ఆమోదించిన పత్రాలు",
        "PAN Card": "పాన్ కార్డు",
        "Driving License": "డ్రైవింగ్ లైసెన్స్",
        "Voter ID": "ఓటరు ఐడీ",
        "This helps us with additional verification (optional).": "అదనపు ధృవీకరణకు ఉపయోగపడుతుంది (ఐచ్ఛికం).",
        "Documents Saved": "పత్రాలు సేవ్ అయ్యాయి",
        "Upload Front Side": "ముందు వైపు అప్‌లోడ్ చేయండి",
        "Upload Back Side": "వెనుక వైపు అప్‌లోడ్ చేయండి",
        "Tap to upload photo": "ఫోటో అప్‌లోడ్ చేయడానికి నొక్కండి",
        "File selected": "ఫైల్ ఎంచుకున్నారు",
        "JPG, PNG, PDF (Max 5 MB)": "JPG, PNG, PDF (గరిష్ఠం 5 MB)",
        "Done": "పూర్తయింది",
        "You can select multiple": "ఒకటి కంటే ఎక్కువ ఎంచుకోవచ్చు",
        "Review your details": "మీ వివరాలు సమీక్షించండి",
        "Review your details before submitting your application.": "దరఖాస్తు పంపే ముందు వివరాలు సమీక్షించండి.",
        "Not provided": "ఇవ్వలేదు",
        "Not selected": "ఎంచుకోలేదు",
        "Not uploaded": "అప్‌లోడ్ చేయలేదు",
        "Front & Back Uploaded": "రెండు వైపులా అప్‌లోడ్ అయ్యాయి",
        "Optional": "ఐచ్ఛికం",
        "Within 5 km": "5 కి.మీ. పరిధిలో",
        "Your details will be verified by our team. We'll notify you once your account is approved.": "మా బృందం మీ వివరాలు ధృవీకరిస్తుంది. మీ ఖాతా ఆమోదం తర్వాత తెలియజేస్తాం.",
        "Submitting...": "పంపుతున్నాం...",
        "Submit Application": "దరఖాస్తు పంపండి",
        "By submitting, you agree to our": "దరఖాస్తు పంపడం ద్వారా మీరు మా",
        "Terms & Conditions": "నిబంధనలు అంగీకరిస్తున్నారు",
        "Submitting your cook application": "మీ వంటవారి దరఖాస్తు పంపుతున్నాం",
        "Submitting your application...": "మీ దరఖాస్తు పంపుతున్నాం...",
        "Uploading documents and saving your details.": "పత్రాలు అప్‌లోడ్ చేసి వివరాలు సేవ్ చేస్తున్నాం.",
        "Uploaded Documents": "అప్‌లోడ్ చేసిన పత్రాలు",
        "Back to documents": "పత్రాలకు తిరిగి వెళ్లండి",
        "Close documents": "పత్రాలు మూసివేయండి",
        "No documents have been uploaded.": "ఏ పత్రాలూ అప్‌లోడ్ కాలేదు.",
        "Status": "స్థితి",
        "document": "పత్రం",
        "documents": "పత్రాలు",
        "Opening...": "తెరుస్తున్నాం...",
        "Open document": "పత్రం తెరవండి",
        "Download document": "పత్రం డౌన్‌లోడ్ చేయండి",
        "Preview is not available for this file type.": "ఈ ఫైల్ రకానికి ప్రివ్యూ అందుబాటులో లేదు.",
        "Registration progress": "నమోదు పురోగతి",
        "Snacks": "చిరుతిళ్లు",
        "Idli": "ఇడ్లీ",
        "Sambar": "సాంబార్",
        "Chapati": "చపాతీ",
        "Vegetable Curry": "కూరగాయల కూర",
        "I love cooking healthy and tasty home-style meals with fresh ingredients.": "తాజా పదార్థాలతో ఆరోగ్యకరమైన రుచికరమైన ఇంటి వంట చేయడం నాకు ఇష్టం.",
        "Aadhaar Front": "ఆధార్ ముందు వైపు",
        "Aadhaar Back": "ఆధార్ వెనుక వైపు",
        "Unable to update availability.": "అందుబాటును మార్చలేకపోయాం.",
        "Unable to open this document.": "ఈ పత్రాన్ని తెరవలేకపోయాం.",
        "Please sign in again to view your documents.": "మీ పత్రాలు చూడటానికి మళ్లీ లాగిన్ అవ్వండి.",
        "Documents are unavailable because Supabase is not configured.": "సేవ కాన్ఫిగర్ కాలేదు కాబట్టి పత్రాలు అందుబాటులో లేవు.",
        "Please sign in to change language.": "భాష మార్చడానికి లాగిన్ అవ్వండి.",
        "Connect Supabase before submitting your application.": "దరఖాస్తు పంపే ముందు సేవను కాన్ఫిగర్ చేయండి.",
        "Your session has expired. Please log in again.": "మీ సెషన్ ముగిసింది. మళ్లీ లాగిన్ అవ్వండి.",
        "Unable to save your cook profile.": "మీ వంటవారి ప్రొఫైల్ సేవ్ చేయలేకపోయాం.",
        "Unable to go online.": "ఆన్‌లైన్‌లోకి వెళ్లలేకపోయాం.",
        "Unable to go offline.": "ఆఫ్‌లైన్‌లోకి వెళ్లలేకపోయాం.",
        "Notifications are blocked. Enable them in your device settings.": "నోటిఫికేషన్‌లు నిలిపివేయబడ్డాయి. పరికర సెట్టింగ్స్‌లో ప్రారంభించండి.",
        "Push notifications are not supported in this browser.": "ఈ బ్రౌజర్ పుష్ నోటిఫికేషన్‌లకు మద్దతు ఇవ్వదు.",
        "Please sign in again to enable notifications.": "నోటిఫికేషన్‌లు ప్రారంభించడానికి మళ్లీ లాగిన్ అవ్వండి.",
        "Notifications are not configured.": "నోటిఫికేషన్ సేవ కాన్ఫిగర్ కాలేదు.",
    },
};

export function translateCook(language: CookLanguage, text: string): string {
    return language === "en" ? text : translations[language][text] ?? text;
}